version: "3.8" #Docker Composeファイルの形式のバージョンを指定
services:
  django:
    build: ./django #イメージを作成する際に./django下にあるDockerfileを参照
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 #起動時に実行される規定のコマンド
    ports:
      - 8000:8000
    volumes:
      - ./src:/code #./srcをコンテナ内の/codeからアクセス可能
    depends_on: #services:dbが起動した後にservices:djangoを起動する
      - db
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data #Dockerが管理するデータストレージ領域postgres-dataをコンテナ内の/var/lib/postgresql/dataにボリューム
        #postgres-dataはPostgreSQLのイメージをビルドした際にできるデータストレージ領域
        #PostgreSQLのイメージでは/var/lib/postgresql/dataがデータの保存場所として決められている
    environment:
      - POSTGRES_USER=learner #ユーザ名を指定
      - POSTGRES_PASSWORD=passwoed #パスワードを指定
      - POSTGRES_DB=testdb #データベース名を指定

volumes:
  postgres-data: #データ永続化


#volumes: postgres-data: => コンテナ全体のボリューム定義、データ保持領域を指定
#servises: db: volumes: postgres-data: => 実際にコンテナ全体のデータ保持領域postgres-dataを/var/lib/postgresql/dataに紐づける