databases:
  - name: sample-db
    plan: free

services:
  - type: web
    name: docker-compose-django-sample
    plan: free
    branch: main
    env: docker
    buildCommand: "docker compose build"
    startCommand: "docker compose up -d"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
