databases:
  - name: sample-db
    plan: free
    databaseName: sampledb
    user: djangotest_sample

services:
  - type: web
    name: django-test
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "uvicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: DATABASE_URL
        fromDatabase:
          name: sample-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4